### ISSUE TITLE
a robot called... is already connected to account

### ISSUE THREAD

**Issue by TheTokenMaster** [dunstad/roboserver#4]
I have installed the server and client (both with default settings) and the robot identified for the account and then seemed to lose it's identity or connection.

The server output:
> unidentified robot connected
id { account: 'oc', robot: 'R2-D2' }
robot R2-D2 identified for account oc
unidentified robot connected
id { account: 'oc', robot: 'R2-D2' }
a robot called R2-D2 is already connected to account oc
unidentified robot connected
robot R2-D2 for account oc disconnected
closed
id { account: 'oc', robot: 'R2-D2' }
robot R2-D2 identified for account oc
closed
unidentified robot connected
id { account: 'oc', robot: 'R2-D2' }
a robot called R2-D2 is already connected to account oc
unidentified robot connected
robot R2-D2 for account oc disconnected
closed
id { account: 'oc', robot: 'R2-D2' }
robot R2-D2 identified for account oc
closed
unidentified robot connected
id { account: 'oc', robot: 'R2-D2' }
a robot called R2-D2 is already connected to account oc
...

**Comment by dunstad** [comment]
All right, let me go through the output here and explain what I'm seeing.

> unidentified robot connected
This is normal, every robot is unidentified when it first connects to the server.

>id { account: 'oc', robot: 'R2-D2' }
>robot R2-D2 identified for account oc
These are both good to see, it shows that initially your robot identified itself and connected successfully to the server.

>a robot called R2-D2 is already connected to account oc
This is expected, because based on the previous server output, your first robot with the name R2-D2 was still connected at the time a second one tried to connect. If you want to have multiple robots connected, give them different names in the settings file!

>robot R2-D2 for account oc disconnected
>closed
This is normal to see when a robot stops listening for commands, which happens when you choose to shut it off or the listener program otherwise stops running.

If I understand the situation correctly, you're trying to connect multiple robots at the same time, but running into a problem because they have the same identifier specified in the settings file. If you check out the bottom of [tips.md](https://github.com/dunstad/roboserver/blob/master/documentation/tips.md), there's a list of all the settings that robots pay attention to, including this one:

>robotName: A unique name for your robot, used to tell it apart from other robots.

Let me know if this helped fix your issue! :)

**Comment by TheTokenMaster** [comment]
Thank you for the explanation.

Unfortunately the situation is that just the one robot successfully connecting the first time, losing connection immediately and then being unable to reconnect under the robot name in the configuration.

**Comment by TheTokenMaster** [comment]
I may have found the problem by running [Wireshark](https://www.wireshark.org/).

By default opencomputers Internet cards can have 4 TCP connections at a time. The robot seems to have opened 2 TCP connections at the same time to which the server has taken objection.

Is this is a bug?

Would any of the following actions help?:
- Have the robot only ever open one TCP connection.
- Have the server tolerate multiple TCP connections from one robot.
- Have the robot close TCP connections before opening new ones.

TCP communication:
> robot opens port	: 39032
39032 --> server	: {"id":{"account":"oc","robot":"R2-D2"}}
server --> 39032	: {"message":"hello, it's the tcp server!"}
server --> 39032	: {"command":{"name":"sendPosition","parameters":[]}}
server --> 39032	: {"command":{"name":"scanArea","parameters":[1]}}
server --> 39032	: {"command":{"name":"sendComponents","parameters":[]}}
robot opens port	: 39034
server --> 39034	: {"message":"hello, it's the tcp server!"}
39034 --> server	: {"id":{"account":"oc","robot":"R2-D2"}}
server --> 39034	: {"message":"a robot called R2-D2 is already connected to account oc"}
server closes port	: 39032
server closes port	: 39034
[Repeat]

Wireshark output file: [tcp.pcapng.gz](https://github.com/dunstad/roboserver/files/1289713/tcp.pcapng.gz)

I hope this helps.

**Comment by dunstad** [comment]
Gotcha, next question. Are you using the most recent push, or one of the [releases?](https://github.com/dunstad/roboserver/releases)

If you're using the most recent stuff, it's being worked on right now, so I'm not surprised this would happen if that's the case.

**Comment by TheTokenMaster** [comment]
I downloaded "roboserver-master.zip" so I think it is the most recent push, I didn't realise it was work in progress.

Thank you.

**Comment by dunstad** [comment]
No worries! I'll try and see what I can do to make it less likely that other people run into this same issue in the future. Hope everything goes smoothly now :)
